export enum ErrorCode {
    LOAN_NOT_FOUND = "LOAN_NOT_FOUND",
    BORROWER_MISMATCH = "BORROWER_MISMATCH",
    INSUFFICIENT_BALANCE = "INSUFFICIENT_BALANCE",
    INVALID_LOAN_ID = "INVALID_LOAN_ID",
    MISSING_FIELD = "MISSING_FIELD",
}
