/**
 * AUTOGENERATED FILE - DO NOT EDIT MANUALLY
 * Generated by scripts/generate-types.mjs from batch-schema.json
 * Single source of truth for batch authorization, receipts, nonces, and error codes.
 */

export type ItemStatus =
  | { type: 'Applied' }
  | { type: 'Skipped'; code: number }
  | { type: 'Reverted'; code: number };

export type OpKind = 'ProcessDefaults' | 'ApproveLoans' | 'GovernanceExecute';

export const OpKindEnum = {
  ProcessDefaults: 0,
  ApproveLoans: 1,
  GovernanceExecute: 2,
} as const;

export interface BatchReceiptItem {
  loanId: string;
  status: ItemStatus;
}

export interface BatchReceiptEvent {
  batchId: string;
  items: BatchReceiptItem[];
}

export const LoanError = {
  NonceReused: 29,
  BatchWindowExpired: 30,
} as const;

export type LoanErrorCode = typeof LoanError[keyof typeof LoanError];

export const GovernanceError = {
  NonceReused: 4022,
} as const;

export type GovernanceErrorCode = typeof GovernanceError[keyof typeof GovernanceError];

export interface BroadcastIdempotencyRecord {
  opKey: string;
  batchId: string;
  nonce: string;
  txHash?: string;
  ledgerSeq?: string;
  status: 'pending' | 'submitted' | 'applied' | 'failed';
  createdAt?: string;
}

export type BatchOpFSMState =
  | 'idle'
  | 'building'
  | 'broadcasting'
  | 'partially_applied'
  | 'reconciling'
  | 'settled'
  | 'failed';
