/**
 * Cross-layer batch-authorization code generator.
 *
 * Reads canonical specification from /batch-schema.json and generates
 * consistent TypeScript type definitions consumed by:
 *   - backend/src/types/batchTypes.generated.ts
 *   - frontend/src/app/types/batchTypes.generated.ts
 *   - packages/contract-types/src/index.ts
 *
 * Usage:
 *   node scripts/generate-types.mjs          # regenerate in place
 *   node scripts/generate-types.mjs --check  # fail if generated files differ (used in CI)
 */
import * as fs from 'fs';
import * as path from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const ROOT = path.resolve(__dirname, '..');
const SCHEMA_PATH = path.join(ROOT, 'batch-schema.json');

const checkOnly = process.argv.includes('--check');

function loadSchema() {
  const content = fs.readFileSync(SCHEMA_PATH, 'utf8');
  return JSON.parse(content);
}

function generateTypeScript(schema) {
  return `/**
 * AUTOGENERATED FILE - DO NOT EDIT MANUALLY
 * Generated by scripts/generate-types.mjs from batch-schema.json
 * Single source of truth for batch authorization, receipts, nonces, and error codes.
 */

export type ItemStatus =
  | { type: 'Applied' }
  | { type: 'Skipped'; code: number }
  | { type: 'Reverted'; code: number };

export type OpKind = 'ProcessDefaults' | 'ApproveLoans' | 'GovernanceExecute';

export const OpKindEnum = {
  ProcessDefaults: 0,
  ApproveLoans: 1,
  GovernanceExecute: 2,
} as const;

export interface BatchReceiptItem {
  loanId: string;
  status: ItemStatus;
}

export interface BatchReceiptEvent {
  batchId: string;
  items: BatchReceiptItem[];
}

export const LoanError = {
  NonceReused: ${schema.error_codes.LoanError.NonceReused},
  BatchWindowExpired: ${schema.error_codes.LoanError.BatchWindowExpired},
} as const;

export type LoanErrorCode = typeof LoanError[keyof typeof LoanError];

export const GovernanceError = {
  NonceReused: ${schema.error_codes.GovernanceError.NonceReused},
} as const;

export type GovernanceErrorCode = typeof GovernanceError[keyof typeof GovernanceError];

export interface BroadcastIdempotencyRecord {
  opKey: string;
  batchId: string;
  nonce: string;
  txHash?: string;
  ledgerSeq?: string;
  status: 'pending' | 'submitted' | 'applied' | 'failed';
  createdAt?: string;
}

export type BatchOpFSMState =
  | 'idle'
  | 'building'
  | 'broadcasting'
  | 'partially_applied'
  | 'reconciling'
  | 'settled'
  | 'failed';
`;
}

function ensureDirectoryExists(dir) {
  if (!fs.existsSync(dir)) {
    fs.mkdirSync(dir, { recursive: true });
  }
}

function main() {
  const schema = loadSchema();
  const tsContent = generateTypeScript(schema);

  const targets = [
    path.join(ROOT, 'backend', 'src', 'types', 'batchTypes.generated.ts'),
    path.join(ROOT, 'frontend', 'src', 'app', 'types', 'batchTypes.generated.ts'),
    path.join(ROOT, 'packages', 'contract-types', 'src', 'index.ts'),
  ];

  let hasDiff = false;

  for (const target of targets) {
    ensureDirectoryExists(path.dirname(target));
    if (fs.existsSync(target)) {
      const existing = fs.readFileSync(target, 'utf8');
      if (existing === tsContent) {
        continue;
      }
    }

    if (checkOnly) {
      console.error(`Diff detected in generated file: ${path.relative(ROOT, target)}`);
      hasDiff = true;
    } else {
      fs.writeFileSync(target, tsContent, 'utf8');
      console.log(`Generated: ${path.relative(ROOT, target)}`);
    }
  }

  if (checkOnly && hasDiff) {
    process.exit(1);
  }
}

main();
